baseurl = "/"
languageCode = "en-us"
title = "Heart Repair Space"

[params]
  description = "It's about death, life, love and repair of the human heart."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
